### ISSUE TITLE
cloudinary bulkk upload

### ISSUE THREAD

**Issue by RichardM1337** [sitechtimes/ai-vs-human-art-backend#21]

**Comment by whydoesthecodenotwork** [comment]
the upload functions could be merged into one endpoint i think?
like if someone wants to upload one file, they could send one file to bulk upload. bulk upload could then use its bulk logic by putting the singular file in an array (`[file]`)

**Comment by RichardM1337** [comment]
You could probably just check how many files there are and determine whether or not to use multer single or array
